#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add NodeJS user.
#======================================================================================================================

bf-adduser node


#======================================================================================================================
# Get NodeJS versions.
#======================================================================================================================

cd /tmp

NODE_VERSION=$(cat NODE_BUILD)
bf-echo "NodeJS version ${NODE_VERSION}."

NPM_VERSION=$(cat NPM_BUILD)
bf-echo "NodeJS Package Manager version ${NPM_VERSION}."

YARN_VERSION=$(cat YARN_BUILD)
bf-echo "Yarn version ${YARN_VERSION}."


#======================================================================================================================
# Install NodeJS and dependencies.
#======================================================================================================================

bf-echo "Installing NodeJS v${NODE_VERSION}..."
chmod +x ./install-node && ./install-node ${NODE_VERSION}
bf-done

bf-echo "Installing additional packages..."
apk add --no-cache \
    npm=${NPM_VERSION} \
    yarn=${YARN_VERSION}
bf-done

bf-done


#======================================================================================================================
# Create version message to output on startup (saves approx. 1s).
#======================================================================================================================

NODE_VERSION=`node --version`
NPM_VERSION=`npm --version`
YARN_VERSION=`yarn --version`
echo "NodeJS ${NODE_VERSION} installed, with NPM v${NPM_VERSION} and Yarn v${YARN_VERSION}." >> /INIT_VERSION
