#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add NodeJS user.
#======================================================================================================================

bf-adduser node


#======================================================================================================================
# Get NodeJS versions.
#======================================================================================================================

cd /tmp

NODE_VERSION=$(cat NODE_BUILD)
bf-echo "NodeJS version ${NODE_VERSION}."

NPM_VERSION=$(cat NPM_BUILD)
bf-echo "NodeJS Packacge Manager version ${NPM_VERSION}."

YARN_VERSION=$(cat YARN_BUILD)
bf-echo "Yarn version ${YARN_VERSION}."


#======================================================================================================================
# Install NodeJS and dependencies.
#======================================================================================================================

bf-echo "Installing NodeJS v${NODE_VERSION}..."

apk add --no-cache \
    nodejs=${NODE_VERSION} \
    npm=${NPM_VERSION} \
    yarn=${YARN_VERSION}

bf-done
