FROM bfren/alpine-s6:alpine<%= ${ALPINE_MINOR} %>-<%= ${BASE_REVISION} %>

ARG BF_IMAGE
ARG BF_VERSION

EXPOSE 3000

COPY ./overlay /
COPY ./<%= ${NODE_MAJOR} %>/NODE_BUILD /tmp/
COPY ./<%= ${NODE_MAJOR} %>/YARN_BUILD /tmp/

RUN bf-install

VOLUME [ "/app/live", "/app/publish" ]
