#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run as Node.js user.
#======================================================================================================================

bf-echo "Starting Node.js server."
s6-setuidgid node /command/with-contenv node ${NODE_RUN}
