#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run as NodeJS user.
#======================================================================================================================

bf-echo "Starting NodeJS server."
s6-setuidgid node node ${NODE_APP_LIVE}/index.js
