name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        node: [ "14", "16", "17", "18", "19", "20" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read Node.js version - minor
        uses: bfren/read-file@v2
        with:
          file: ./${{ matrix.node }}/overlay/tmp/NODE_MINOR
        id: node_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.node }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bfren/node:node${{ matrix.node }}
            bfren/node:node${{ matrix.node }}-${{ steps.version_major.outputs.contents }}
            bfren/node:node${{ matrix.node }}-${{ steps.version_minor.outputs.contents }}
            bfren/node:node${{ matrix.node }}-${{ steps.version.outputs.contents }}
            bfren/node:node${{ steps.node_minor.outputs.contents }}
            bfren/node:node${{ steps.node_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default
        id: docker_build_default
        if: matrix.node == '20'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.node }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bfren/node:latest
            bfren/node:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
